### ISSUE TITLE
Problem on a Debian system during make

### ISSUE THREAD

**Issue by parfington** [poschengband/poschengband#37]
Entering directory src
/usr/bin/ld: -r and -pie may not be used together
collect2: error: ld returned 1 exit status
Makefile:35: recipe for target 'poschengband.o' failed
make[3]: *** [poschengband.o] Error 1
../mk/buildsys.mk:110: recipe for target 'all' failed
make[2]: *** [all] Error 2
mk/buildsys.mk:115: recipe for target 'subdirs' failed
make[1]: *** [subdirs] Error 2
mk/buildsys.mk:110: recipe for target 'all' failed
make: *** [all] Error 2

this is what happens, everything else went as planned up until this point and I can't find any information regarding this error on the net, so here I am! any help would be much appreciated!

**Comment by parfington** [comment]
ah! scratch that, found something that solved the problem, but it could be useful to keep this solution up for anyone who experiences something similar!
http://angband.oook.cz/forum/showthread.php?t=8178
credit to takkaria!

**Comment by Raptime** [comment]
I ran into the same issue, maybe keep the issue open until it's fixed
What I did:
-no-pie should be added to line 30 of src/Makefile
